'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { employeeForgotPin, employeeLogin } from '@/lib/api';

export default function EmployeeLoginPage() {
  const router = useRouter();

  const [employeeNumber, setEmployeeNumber] = useState('STH-000002');
  const [pin, setPin] = useState('');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [loading, setLoading] = useState(false);
  const [resetPin, setResetPin] = useState('');

  function saveEmployeeSession(result: any) {
    const token = result?.token;
    const resolvedEmployeeNumber =
      result?.employee?.employeeNumber || employeeNumber.trim();

    if (token) {
      localStorage.setItem('peoplepay_employee_token', token);
      localStorage.setItem('peoplepay_employee_number', resolvedEmployeeNumber);

      localStorage.setItem('employeeToken', token);
      localStorage.setItem('employeeNumber', resolvedEmployeeNumber);

      localStorage.setItem('southin_peoplepay_employee_token', token);
    }
  }

  async function handleLogin(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    setError('');
    setNotice('');
    setLoading(true);

    try {
      const result = await employeeLogin({
        employeeNumber: employeeNumber.trim(),
        pin: pin.trim(),
      });

      saveEmployeeSession(result);

      if (result.mustChangePin) {
        router.push('/first-login-change-pin');
        return;
      }

      router.push('/me');
    } catch {
      setError(
        'Invalid employee number or PIN. If you used Forgot PIN, use the latest temporary PIN generated by the system.',
      );
    } finally {
      setLoading(false);
    }
  }

  async function handleForgotPin() {
    setError('');
    setNotice('');
    setResetPin('');

    if (!employeeNumber.trim()) {
      setError('Enter your employee number first, then click Forgot PIN.');
      return;
    }

    setLoading(true);

    try {
      const result = await employeeForgotPin({
        employeeNumber: employeeNumber.trim(),
      });

      if (result.temporaryPin) {
        setResetPin(result.temporaryPin);
        setPin(result.temporaryPin);

        setNotice(
          `Development mode: temporary PIN generated and inserted in the PIN field. In production this will be emailed to ${result.email || 'the employee email address'}.`,
        );
      } else {
        setNotice(
          result.message ||
            'If your employee number is valid, a temporary PIN reset email will be sent.',
        );
      }
    } catch {
      setError('Failed to request PIN reset. Please contact HR or IT.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="auth-page">
      <section className="auth-card">
        <h1>Employee Login</h1>

        <p className="muted">
          Use your Employee Number and PIN to access your Southin PeoplePay employee portal.
        </p>

        <form onSubmit={handleLogin}>
          <label>
            Employee Number
            <input
              value={employeeNumber}
              onChange={(event) => setEmployeeNumber(event.target.value)}
              placeholder="STH-000002"
              required
            />
          </label>

          <label>
            PIN
            <input
              value={pin}
              onChange={(event) => setPin(event.target.value)}
              placeholder="Temporary or changed PIN"
              type="password"
              required
            />
          </label>

          {resetPin && (
            <div className="notice">
              Temporary PIN for development testing: <strong>{resetPin}</strong>
            </div>
          )}

          {error && <div className="notice">{error}</div>}
          {notice && <div className="notice">{notice}</div>}

          <div className="action-row">
            <button className="btn" disabled={loading} type="submit">
              {loading ? 'Signing in...' : 'Login'}
            </button>

            <button
              className="link-button"
              disabled={loading}
              onClick={handleForgotPin}
              type="button"
            >
              Forgot PIN?
            </button>
          </div>
        </form>
      </section>
    </main>
  );
}